export const BEGIN_AJAX_CALL = "BEGIN_AJAX_CALL";
export const AJAX_CALL_ERROR = "AJAX_CALL_ERROR";

export const LOAD_GENERICS_SUCCESS = "LOAD_GENERICS_SUCCESS";
export const CREATE_GENERIC_SUCCESS = "CREATE_GENERIC_SUCCESS";
export const UPDATE_GENERIC_SUCCESS = "UPDATE_GENERIC_SUCCESS";
export const LOAD_TASTES_SUCCESS = "LOAD_TASTES_SUCCESS";

export const GET_ALL_UMAMI_SUCCESS = "GET_ALL_UMAMI_SUCCESS";
